name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python tooling
        run: |
          pip install \
            black==24.8.0 \
            pylint==3.2.6 \
            yamllint==1.35.1 \
            pyyaml==6.0.2

      - name: Black - check formatting
        run: |
          black --check --diff .

      - name: Pylint - lint Python files
        shell: bash
        run: |
          set -e
          FILES=$(git ls-files '*.py' | grep -v '^ext/')
          if [ -z "$FILES" ]; then
            echo "No Python files to lint." && exit 0
          fi
          pylint --rcfile=.pylintrc $FILES

      - name: YAML Lint - GitHub workflows
        run: |
          yamllint -d '{extends: default, rules: {line-length: disable, truthy: disable}}' .github/workflows || true

      - name: YAML Validate - telegrams (parse + project rules)
        run: |
          python tools/validate_telegrams.py

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: ShellCheck - bin scripts
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          files=(bin/**/*.sh bin/*.sh bin/service/run bin/service/log/run)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No shell scripts found." && exit 0
          fi
          shellcheck -x "${files[@]}"

